pull_request_title: Update translations
commit_message: Update translations (%language%)
append_commit_message: false

files:
  - source: /LinearMouse/en.lproj/Localizable.strings
    translation: /LinearMouse/%osx_code%/%original_file_name%
