name: Bug report
description: Create a report to help us improve.
title: "[BUG] "
labels: bug
body:
- type: input
  id: os
  attributes:
    label: OS
    placeholder: macOS 13.1 (Build 22C65)
  validations:
    required: true
- type: input
  id: linearmouse
  attributes:
    label: LinearMouse
    placeholder: v0.7.5
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: To reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
