name: Feature request
description: Suggest an idea for this project.
title: "[Feature] "
labels: enhancement
body:
- type: input
  id: os
  attributes:
    label: OS
    placeholder: macOS 13.1 (Build 22C65)
  validations:
    required: false
- type: input
  id: linearmouse
  attributes:
    label: LinearMouse
    placeholder: v0.7.5
  validations:
    required: false
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: A clear and concise description of what the problem is.
    placeholder: I'm always frustrated when [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
    placeholder: I'd like to have per-app settings [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context or screenshots about the feature request here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
